# %% [markdown]
# # Irreps of $C_n^3 \rtimes A_4$ from $C_n^3$
#
# Three-dimensional counterpart of Panel B of Figure 8 (the $C_6$ orbit of characters of $C_n^2$). Translation characters
# are $\chi_\xi(a)=\cos(2\pi\,\xi\cdot a/n)$, indexed by $\xi\in\mathbb Z_n^3$. The tetrahedral group $A_4\subset\mathrm{GL}(3,\mathbb Z)$,
# generated by $D=\mathrm{diag}(1,-1,-1)$ and the cyclic permutation $P$, acts on frequencies by orthogonal matrices, so
# an $A_4$ orbit collects the Fourier components that induce one spatial irrep of $C_n^3\rtimes A_4$.
#
# A function on $\mathbb Z_n^3$ is drawn as a cube whose three visible faces carry its slices $a_1=0$, $a_2=0$, $a_3=0$
# (the convention of Figure 10 in the appendix). Left: one such glyph at every point of the orbit of $\xi_0$, inside the
# block of frequency cells $\{-3,\dots,3\}^3$, with solid arrows for $P$ (coloured by $\langle P\rangle$-orbit) and dashed
# double arrows for $D$. Each glyph drops a stem to its footprint on the floor, so its cell can be read on the grid. Top
# right: the orbit sum $\mathrm{Re}\sum_{q\in\mathcal O_{\xi_0}}\chi_q$. Bottom right: the orbit sums of every $A_4$ orbit
# of $\mathbb Z^3$ ordered by $|\xi|^2$ up to $|\xi_0|^2$, the chosen orbit framed in black. Since $-I\notin A_4$, the orbits
# $\mathcal O_\xi$ and $-\mathcal O_\xi$ are distinct (they induce conjugate irreps) but have the same real part, so each
# tile stands for one such pair, i.e. one orbit of the pyritohedral group $A_4\times\{\pm I\}$.

# %%
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import FancyArrowPatch, Polygon

plt.rcParams["svg.fonttype"] = "none"
plt.rcParams["font.family"] = ["Century Gothic", "TeX Gyre Adventor", "DejaVu Sans"]   # first one installed wins
plt.rcParams["mathtext.fontset"] = "custom"
for key, style in (("rm", ""), ("it", ":italic"), ("bf", ":bold"), ("sf", "")):
    plt.rcParams[f"mathtext.{key}"] = "Century Gothic, TeX Gyre Adventor, DejaVu Sans" + style
plt.rcParams["mathtext.fallback"] = "cm"

project_root = next((folder for folder in (Path.cwd(), *Path.cwd().parents) if (folder / "src").is_dir()), Path.cwd())
figures = project_root / "artifacts" / "constructed_networks" / "discrete_se3_a4" / "paper_figures"
figures.mkdir(parents=True, exist_ok=True)

n = 60                                   # spatial resolution, as in Figure 10 of the appendix
xi_0 = np.array([1, 2, 3])               # a frequency with trivial stabiliser
sheet_frequencies = np.arange(-3, 4)     # the block of frequency cells drawn on the left
output_name = "irreps_cn3_a4.svg"

# --- the tetrahedral group A_4 and its orbits -----------------------------------------------------------------------------
D = np.diag([1, -1, -1])
P = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]])
group, frontier = [np.eye(3, dtype=int)], [np.eye(3, dtype=int)]
while frontier:                          # closure of {D, P}: the twelve rotations of the tetrahedron
    new = []
    for g in frontier:
        for h in (D, P):
            candidate = h @ g
            if not any(np.array_equal(candidate, k) for k in group):
                group.append(candidate)
                new.append(candidate)
    frontier = new
assert len(group) == 12

as_tuple = lambda v: tuple(int(x) for x in v)
orbit_of = lambda q: sorted({as_tuple(g @ np.asarray(q)) for g in group})   # orthogonal matrices act on frequencies directly

orbit = orbit_of(xi_0)
assert len(orbit) == 12, "xi_0 must have trivial stabiliser"
three_cycles = []                         # the four <P>-orbits inside the A_4 orbit, the one through xi_0 first (blue)
for q in [as_tuple(xi_0), *orbit]:
    cycle = tuple(as_tuple(np.linalg.matrix_power(P, i) @ np.array(q)) for i in range(3))
    if not any(set(cycle) == set(c) for c in three_cycles):
        three_cycles.append(cycle)
colour_of = {q: colour for cycle, colour in zip(three_cycles, ("#00A6FF", "#FF5A36", "#00C853", "#B040FF"), strict=True) for q in cycle}

# --- face slices of characters and orbit sums ----------------------------------------------------------------------------
row, col = np.meshgrid(np.arange(n), np.arange(n), indexing="ij")
# Top face a3=0 shows (a1, a2), right face a1=0 shows (a2, a3), left face a2=0 shows (a1, a3); rows are the second coordinate.
face_axes = {"+z": (0, 1), "+x": (1, 2), "+y": (0, 2)}
character_faces = lambda q: {face: np.cos(2 * np.pi * (q[u] * col + q[v] * row) / n) for face, (u, v) in face_axes.items()}


def orbit_sum_faces(frequencies):
    # Real part of the orbit sum on the three faces, mapped jointly to [0, 1] for display.
    faces = {face: sum(character_faces(q)[face] for q in frequencies) for face in face_axes}
    low, high = min(f.min() for f in faces.values()), max(f.max() for f in faces.values())
    if high - low < 1e-9:                                           # the trivial orbit {0}: a constant at its maximum
        return {face: np.ones_like(f) for face, f in faces.items()}
    return {face: (f - low) / (high - low) for face, f in faces.items()}


# --- an orthographic camera in the (+,+,+) octant, and cube glyphs ---------------------------------------------------------
azimuth, elevation = np.deg2rad(44), np.deg2rad(30)       # chosen so the twelve orbit points stay apart on screen
view = np.array([np.cos(elevation) * np.cos(azimuth), np.cos(elevation) * np.sin(azimuth), np.sin(elevation)])
right = np.array([-np.sin(azimuth), np.cos(azimuth), 0.0])
up = np.array([-np.sin(elevation) * np.cos(azimuth), -np.sin(elevation) * np.sin(azimuth), np.cos(elevation)])
project = lambda v: np.array([np.dot(v, right), np.dot(v, up)])
depth = lambda v: float(np.dot(v, view))
unit = np.eye(3)
colormap = plt.get_cmap("coolwarm")
face_shading = {"+z": 1.0, "+x": 0.86, "+y": 0.74}
face_frame = {"+z": ((-1, -1, 1), 0, 1), "+x": ((1, -1, -1), 1, 2), "+y": ((-1, 1, -1), 0, 2)}   # corner, column axis, row axis


def rasterize_face(image_rgb, origin, col_vector, row_vector, pixels_per_unit):
    # Warp a face image onto its projected parallelogram; outside the parallelogram the raster is transparent.
    corners = np.array([origin, origin + col_vector, origin + col_vector + row_vector, origin + row_vector])
    (x0, y0), (x1, y1) = corners.min(axis=0), corners.max(axis=0)
    width, height = max(int(np.ceil((x1 - x0) * pixels_per_unit)), 2), max(int(np.ceil((y1 - y0) * pixels_per_unit)), 2)
    xs = x0 + (np.arange(width) + 0.5) * (x1 - x0) / width
    ys = y0 + (np.arange(height) + 0.5) * (y1 - y0) / height
    uv = (np.stack(np.meshgrid(xs, ys), axis=-1) - origin) @ np.linalg.inv(np.column_stack([col_vector, row_vector])).T
    inside = np.all((uv >= 0) & (uv < 1), axis=-1)
    rows, cols = image_rgb.shape[:2]
    j = np.clip((uv[..., 1] * rows).astype(int), 0, rows - 1)
    i = np.clip((uv[..., 0] * cols).astype(int), 0, cols - 1)
    rgba = np.zeros((height, width, 4))
    rgba[..., :3], rgba[..., 3] = image_rgb[j, i], inside
    return rgba, (x0, x1, y0, y1), corners


def draw_cube(ax, centre, half, faces, edgecolor="black", linewidth=1.2, zorder=1, pixels_per_unit=200, shift=(0.0, 0.0)):
    # faces: {"+z", "+x", "+y"} -> image in [0, 1], drawn with coolwarm on the three visible faces of the cube.
    # shift moves the projected glyph on screen, for laying out glyphs on a 2D grid.
    centre = np.asarray(centre, dtype=float)
    for face, (corner, col_axis, row_axis) in face_frame.items():
        origin = project(centre + half * np.array(corner)) + np.asarray(shift, float)
        col_vector, row_vector = project(2 * half * unit[col_axis]), project(2 * half * unit[row_axis])
        rgb = colormap(np.clip(faces[face], 0, 1))[..., :3] * face_shading[face]
        rgba, extent, corners = rasterize_face(rgb, origin, col_vector, row_vector, pixels_per_unit)
        ax.imshow(rgba, origin="lower", extent=extent, interpolation="antialiased", zorder=zorder)
        ax.add_patch(Polygon(corners, closed=True, fill=False, edgecolor=edgecolor, linewidth=linewidth, joinstyle="round",
                             zorder=zorder + 0.5))


def segment(ax, start, end, zorder=0, **style):
    ax.plot(*zip(project(np.asarray(start, float)), project(np.asarray(end, float))), zorder=zorder, **style)


def draw_cell_wireframe(ax, centre, half, zorder, split_depth, **style):
    # The twelve edges of a cube; edges nearer the camera than split_depth go just above zorder, the others just below.
    centre = np.asarray(centre, float)
    for axis in range(3):
        for other in np.ndindex(2, 2):
            start = centre.copy()
            start[[(axis + 1) % 3, (axis + 2) % 3]] += half * (2 * np.array(other) - 1)
            start[axis] -= half
            end = start.copy()
            end[axis] += 2 * half
            segment(ax, start, end, zorder=zorder + (0.7 if depth((start + end) / 2) > split_depth else -0.7), **style)


# --- figure -------------------------------------------------------------------------------------------------------------
figure = plt.figure(figsize=(8.6, 6.6))
figure.text(0.012, 0.985, r"Irreps of $C_n^3 \rtimes A_4$ from $C_n^3$", fontsize=17, fontweight="bold", va="top")

# Left: the orbit inside the block of frequency cells.
bank = figure.add_axes((-0.01, 0.0, 0.66, 0.92))
bank.set_aspect("equal")
bank.axis("off")
block = sheet_frequencies[-1] + 0.5
cell_edges = np.arange(-block, block + 1)
for wall_axis in range(3):                                          # grids on the three far walls
    u_axis, v_axis = (wall_axis + 1) % 3, (wall_axis + 2) % 3
    for value in cell_edges:
        for line_axis, other_axis in ((u_axis, v_axis), (v_axis, u_axis)):
            start, end = np.zeros(3), np.zeros(3)
            start[wall_axis] = end[wall_axis] = -block
            start[other_axis] = end[other_axis] = value
            start[line_axis], end[line_axis] = -block, block
            segment(bank, start, end, zorder=-5, color="0.72", linewidth=0.45)
draw_cell_wireframe(bank, (0, 0, 0), block, zorder=-4, split_depth=depth(np.zeros(3)), color="0.35", linewidth=0.9)
for axis, anchor, offset in ((0, np.array([0, block, -block]), np.array([0.0, -0.38])),     # ticks on two front bottom edges
                             (1, np.array([block, 0, -block]), np.array([0.0, -0.38])),     # and on the left vertical edge
                             (2, np.array([block, -block, 0]), np.array([-0.38, 0.0]))):
    for tick in sheet_frequencies:
        position = anchor.astype(float)
        position[axis] = tick
        bank.text(*(project(position) + offset), str(tick), ha="center", va="center", fontsize=9, color="0.35", zorder=300)
    label_position = anchor.astype(float)
    label_position[axis] = 0
    bank.text(*(project(label_position) + 2.6 * offset), (r"$\xi_1$", r"$\xi_2$", r"$\xi_3$")[axis], ha="center", va="center",
              fontsize=13, color="0.25", zorder=300)
bank.plot(*project(np.zeros(3)), marker="o", markersize=4.5, color="black", zorder=-1)

half = 0.30
glyph_depth = {q: depth(np.array(q, dtype=float)) for q in orbit}
order = sorted(orbit, key=glyph_depth.get)                          # far glyphs first
for rank, q in enumerate(order):
    z = 10 + 2 * rank
    draw_cube(bank, q, half, character_faces(q), edgecolor=colour_of[q], linewidth=2.2, zorder=z)
    draw_cell_wireframe(bank, q, 0.5, zorder=z, split_depth=glyph_depth[q], color=colour_of[q], linewidth=0.8, alpha=0.75)
    footprint = np.array([q[0], q[1], -block], dtype=float)           # stem to the floor, footprint marks the (xi_1, xi_2) cell
    segment(bank, footprint, np.array([q[0], q[1], q[2] - half], dtype=float), zorder=z - 1, color=colour_of[q], linewidth=0.7,
            alpha=0.6, linestyle=(0, (2, 1.5)))
    bank.plot(*project(footprint), marker="o", markersize=3.4, color=colour_of[q], markeredgecolor="white", markeredgewidth=0.5,
              linewidth=0, zorder=z - 1)
    bank.annotate(rf"$({q[0]},{q[1]},{q[2]})$", project(np.array(q, float)) + np.array([0, -half * 2.1]), ha="center", va="top",
                  fontsize=8.5, color="0.2", zorder=200, bbox=dict(boxstyle="round,pad=0.12", facecolor="white", edgecolor="none", alpha=0.75))
for q in orbit:                                                     # P arrows solid, D arrows dashed and double headed
    for generator, style in ((P, dict(arrowstyle="-|>", linestyle="-", color=colour_of[q], linewidth=1.4)),
                             (D, dict(arrowstyle="<|-|>", linestyle=(0, (3, 2)), color="0.55", linewidth=0.9))):
        target = as_tuple(generator @ np.array(q))
        if generator is D and q > target:
            continue                                                # each unordered D-pair once
        bank.add_patch(FancyArrowPatch(project(np.array(q, float)), project(np.array(target, float)), mutation_scale=11,
                                       shrinkA=21, shrinkB=21, zorder=10 + 2 * min(order.index(q), order.index(target)) + 1, **style))
bank.set(xlim=(-6.4, 6.3), ylim=(-6.2, 5.3))

# Top right: the orbit sum of xi_0.
sum_axes = figure.add_axes((0.66, 0.47, 0.34, 0.45))
sum_axes.set_aspect("equal")
sum_axes.axis("off")
draw_cube(sum_axes, (0, 0, 0), 1.0, orbit_sum_faces(orbit), linewidth=3.2, pixels_per_unit=380)
sum_axes.set(xlim=(-1.7, 1.7), ylim=(-1.6, 1.6))

# Bottom right: one tile per pair of conjugate orbits {O(xi), -O(xi)} with |xi|^2 <= |xi_0|^2, ordered by |xi|^2 (ties broken
# lexicographically), the pair containing xi_0 framed. Both orbits of a pair have the same real part.
negated = lambda frequencies: sorted(tuple(-x for x in q) for q in frequencies)
representatives, seen = [], set()
for q in sorted(np.ndindex(*(2 * sheet_frequencies[-1] + 1,) * 3), key=lambda p: (sum((x - 3) ** 2 for x in p), p)):
    q = tuple(x - sheet_frequencies[-1] for x in q)
    if q in seen or sum(x * x for x in q) > int(xi_0 @ xi_0):
        continue
    orbit_q = orbit_of(q)
    seen.update(orbit_q + negated(orbit_q))
    representatives.append(max(orbit_q + negated(orbit_q)))
columns = 5
rows = int(np.ceil((len(representatives) + 1) / columns))
tiles = figure.add_axes((0.66, 0.01, 0.34, 0.44))
tiles.set_aspect("equal")
tiles.axis("off")
pitch = 3.0
for index, q in enumerate(representatives):
    chosen = as_tuple(xi_0) in orbit_of(q) + negated(orbit_of(q))
    draw_cube(tiles, (0, 0, 0), 1.0, orbit_sum_faces(orbit_of(q)), linewidth=2.6 if chosen else 0.4, pixels_per_unit=110,
              shift=((index % columns) * pitch, -(index // columns) * pitch))
end = np.array([(len(representatives) % columns) * pitch, -(len(representatives) // columns) * pitch])
tiles.add_patch(FancyArrowPatch(end + np.array([-0.9, 0.0]), end + np.array([1.1, 0.0]), arrowstyle="-|>", mutation_scale=14,
                                color="black", linewidth=1.8, zorder=3))
tiles.set(xlim=(-1.7, (columns - 1) * pitch + 1.7), ylim=(-(rows - 1) * pitch - 1.7, 1.7))

path = figures / output_name
figure.savefig(path, bbox_inches="tight")
figure.savefig(path.with_suffix(".png"), dpi=200, bbox_inches="tight")
plt.close(figure)
# Record the intended typeface in the SVG even when only the metric-compatible fallback is installed here.
svg = path.read_text()
for fallback in ("TeX Gyre Adventor", "DejaVu Sans"):
    svg = svg.replace(f"font-family: '{fallback}'", "font-family: 'Century Gothic', 'TeX Gyre Adventor', sans-serif")
    svg = svg.replace(f'font-family="{fallback}"', 'font-family="Century Gothic, TeX Gyre Adventor, sans-serif"')
path.write_text(svg)
print(f"Saved SVG: {path}")
